// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vRFGcjoeyA4UNF36wYbYzx
// Component: rft30UUNBM-6c
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_plasmic_kit_website_documentation.module.css"; // plasmic-import: vRFGcjoeyA4UNF36wYbYzx/projectcss
import * as sty from "./PlasmicAnnouncement.module.css"; // plasmic-import: rft30UUNBM-6c/css

export type PlasmicAnnouncement__VariantMembers = {};

export type PlasmicAnnouncement__VariantsArgs = {};
type VariantPropType = keyof PlasmicAnnouncement__VariantsArgs;
export const PlasmicAnnouncement__VariantProps = new Array<VariantPropType>();

export type PlasmicAnnouncement__ArgsType = {};
type ArgPropType = keyof PlasmicAnnouncement__ArgsType;
export const PlasmicAnnouncement__ArgProps = new Array<ArgPropType>();

export type PlasmicAnnouncement__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultAnnouncementProps {
  className?: string;
}

function PlasmicAnnouncement__RenderFunc(props: {
  variants: PlasmicAnnouncement__VariantsArgs;
  args: PlasmicAnnouncement__ArgsType;
  overrides: PlasmicAnnouncement__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={p.PlasmicLink}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      component={Link}
      href={
        "https://medium.com/plasmic-app/announcing-plasmic-3bc510a97ea3" as const
      }
      platform={"nextjs"}
    >
      <img
        alt={""}
        className={classNames(defaultcss.img, sty.img__yNs3X)}
        role={"img"}
        src={
          "/plasmic/copy_of_plasmic_kit_website_documentation/images/image6.svg"
        }
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__cKtxL)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__ptbFu
          )}
        >
          {"Read our announcement post on Medium!"}
        </div>

        <img
          alt={""}
          className={classNames(defaultcss.img, sty.img___3Unk)}
          role={"img"}
          src={
            "/plasmic/copy_of_plasmic_kit_website_documentation/images/image8.svg"
          }
        />
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAnnouncement__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicAnnouncement__VariantsArgs;
  args?: PlasmicAnnouncement__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicAnnouncement__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicAnnouncement__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAnnouncement__ArgProps,
      internalVariantPropNames: PlasmicAnnouncement__VariantProps
    });

    return PlasmicAnnouncement__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAnnouncement";
  } else {
    func.displayName = `PlasmicAnnouncement.${nodeName}`;
  }
  return func;
}

export const PlasmicAnnouncement = Object.assign(
  // Top-level PlasmicAnnouncement renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicAnnouncement
    internalVariantProps: PlasmicAnnouncement__VariantProps,
    internalArgProps: PlasmicAnnouncement__ArgProps
  }
);

export default PlasmicAnnouncement;
/* prettier-ignore-end */
