// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vRFGcjoeyA4UNF36wYbYzx
// Component: 77F74dU3Tpm0J
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_plasmic_kit_website_documentation.module.css"; // plasmic-import: vRFGcjoeyA4UNF36wYbYzx/projectcss
import * as sty from "./PlasmicNavigationListItem.module.css"; // plasmic-import: 77F74dU3Tpm0J/css

export type PlasmicNavigationListItem__VariantMembers = {
  styles: "active" | "title" | "link";
  indent: "sublink";
};

export type PlasmicNavigationListItem__VariantsArgs = {
  styles?: MultiChoiceArg<"active" | "title" | "link">;
  indent?: SingleChoiceArg<"sublink">;
};

type VariantPropType = keyof PlasmicNavigationListItem__VariantsArgs;
export const PlasmicNavigationListItem__VariantProps = new Array<VariantPropType>(
  "styles",
  "indent"
);

export type PlasmicNavigationListItem__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicNavigationListItem__ArgsType;
export const PlasmicNavigationListItem__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicNavigationListItem__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultNavigationListItemProps {
  children?: React.ReactNode;
  styles?: MultiChoiceArg<"active" | "title" | "link">;
  indent?: SingleChoiceArg<"sublink">;
  className?: string;
}

function PlasmicNavigationListItem__RenderFunc(props: {
  variants: PlasmicNavigationListItem__VariantsArgs;
  args: PlasmicNavigationListItem__ArgsType;
  overrides: PlasmicNavigationListItem__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__indent_sublink]: hasVariant(variants, "indent", "sublink"),
        [sty.root__styles_active]: hasVariant(variants, "styles", "active"),
        [sty.root__styles_link]: hasVariant(variants, "styles", "link"),
        [sty.root__styles_title]: hasVariant(variants, "styles", "title")
      })}
    >
      <p.PlasmicSlot
        defaultContents={"Welcome"}
        value={args.children}
        className={classNames(sty.slotChildren, {
          [sty.slotChildren__styles_active]: hasVariant(
            variants,
            "styles",
            "active"
          ),
          [sty.slotChildren__styles_link]: hasVariant(
            variants,
            "styles",
            "link"
          ),
          [sty.slotChildren__styles_title]: hasVariant(
            variants,
            "styles",
            "title"
          )
        })}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavigationListItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicNavigationListItem__VariantsArgs;
  args?: PlasmicNavigationListItem__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicNavigationListItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicNavigationListItem__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavigationListItem__ArgProps,
      internalVariantPropNames: PlasmicNavigationListItem__VariantProps
    });

    return PlasmicNavigationListItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavigationListItem";
  } else {
    func.displayName = `PlasmicNavigationListItem.${nodeName}`;
  }
  return func;
}

export const PlasmicNavigationListItem = Object.assign(
  // Top-level PlasmicNavigationListItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNavigationListItem
    internalVariantProps: PlasmicNavigationListItem__VariantProps,
    internalArgProps: PlasmicNavigationListItem__ArgProps
  }
);

export default PlasmicNavigationListItem;
/* prettier-ignore-end */
