// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vRFGcjoeyA4UNF36wYbYzx
// Component: i96nygaM4vRoX
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_plasmic_kit_website_documentation.module.css"; // plasmic-import: vRFGcjoeyA4UNF36wYbYzx/projectcss
import * as sty from "./PlasmicValIcon2.module.css"; // plasmic-import: i96nygaM4vRoX/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: EqfgjatM1Vc9o-/icon

export type PlasmicValIcon2__VariantMembers = {};

export type PlasmicValIcon2__VariantsArgs = {};
type VariantPropType = keyof PlasmicValIcon2__VariantsArgs;
export const PlasmicValIcon2__VariantProps = new Array<VariantPropType>();

export type PlasmicValIcon2__ArgsType = {};
type ArgPropType = keyof PlasmicValIcon2__ArgsType;
export const PlasmicValIcon2__ArgProps = new Array<ArgPropType>();

export type PlasmicValIcon2__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultValIcon2Props {
  className?: string;
}

function PlasmicValIcon2__RenderFunc(props: {
  variants: PlasmicValIcon2__VariantsArgs;
  args: PlasmicValIcon2__ArgsType;
  overrides: PlasmicValIcon2__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Icon3Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicValIcon2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicValIcon2__VariantsArgs;
  args?: PlasmicValIcon2__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicValIcon2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicValIcon2__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicValIcon2__ArgProps,
      internalVariantPropNames: PlasmicValIcon2__VariantProps
    });

    return PlasmicValIcon2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValIcon2";
  } else {
    func.displayName = `PlasmicValIcon2.${nodeName}`;
  }
  return func;
}

export const PlasmicValIcon2 = Object.assign(
  // Top-level PlasmicValIcon2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicValIcon2
    internalVariantProps: PlasmicValIcon2__VariantProps,
    internalArgProps: PlasmicValIcon2__ArgProps
  }
);

export default PlasmicValIcon2;
/* prettier-ignore-end */
