// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vRFGcjoeyA4UNF36wYbYzx
// Component: meefYOLOjb-nqC
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TemplateTile from "../../TemplateTile"; // plasmic-import: TSGvnOEFxSlgUC/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_plasmic_kit_website_documentation.module.css"; // plasmic-import: vRFGcjoeyA4UNF36wYbYzx/projectcss
import * as sty from "./PlasmicTemplateGroup.module.css"; // plasmic-import: meefYOLOjb-nqC/css

import Check2Icon from "./icons/PlasmicIcon__Check2"; // plasmic-import: Sd2-pTAvnwkFbk/icon

export type PlasmicTemplateGroup__VariantMembers = {};

export type PlasmicTemplateGroup__VariantsArgs = {};
type VariantPropType = keyof PlasmicTemplateGroup__VariantsArgs;
export const PlasmicTemplateGroup__VariantProps = new Array<VariantPropType>();

export type PlasmicTemplateGroup__ArgsType = {
  title?: React.ReactNode;
};

type ArgPropType = keyof PlasmicTemplateGroup__ArgsType;
export const PlasmicTemplateGroup__ArgProps = new Array<ArgPropType>("title");

export type PlasmicTemplateGroup__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
  container?: p.Flex<"div">;
};

export interface DefaultTemplateGroupProps {
  title?: React.ReactNode;
  className?: string;
}

function PlasmicTemplateGroup__RenderFunc(props: {
  variants: PlasmicTemplateGroup__VariantsArgs;
  args: PlasmicTemplateGroup__ArgsType;
  overrides: PlasmicTemplateGroup__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        <p.PlasmicSlot defaultContents={"Subheading"} value={args.title} />
      </div>

      <p.Stack
        as={"div"}
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        hasGap={true}
        className={classNames(defaultcss.all, sty.container)}
      >
        <TemplateTile
          image={"withImage" as const}
          instruction={
            "Strongly recommended! Plasmic's power lies in its more advanced concepts."
          }
          name={"3-Minute Codegen Quickstart"}
        >
          <Check2Icon
            className={classNames(defaultcss.all, sty.svg__d5Eb)}
            role={"img"}
          />
        </TemplateTile>

        <TemplateTile
          className={classNames("__wab_instance", sty.templateTile__nmkJx)}
          image={"withImage" as const}
          instruction={
            "Strongly recommended! Plasmic's power lies in its more advanced concepts."
          }
          name={"3-Minute Codegen Quickstart"}
        >
          <Check2Icon
            className={classNames(defaultcss.all, sty.svg__qufic)}
            role={"img"}
          />
        </TemplateTile>

        <TemplateTile
          className={classNames("__wab_instance", sty.templateTile__r93Ik)}
          image={"withImage" as const}
          instruction={
            "Strongly recommended! Plasmic's power lies in its more advanced concepts."
          }
          name={"3-Minute Codegen Quickstart"}
        >
          <Check2Icon
            className={classNames(defaultcss.all, sty.svg__pOlc8)}
            role={"img"}
          />
        </TemplateTile>

        <TemplateTile
          className={classNames("__wab_instance", sty.templateTile__zP0G0)}
          image={"withImage" as const}
          instruction={
            "Strongly recommended! Plasmic's power lies in its more advanced concepts."
          }
          name={"3-Minute Codegen Quickstart"}
        >
          <Check2Icon
            className={classNames(defaultcss.all, sty.svg__d7G0G)}
            role={"img"}
          />
        </TemplateTile>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box", "container"],
  box: ["box"],
  container: ["container"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
  container: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTemplateGroup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicTemplateGroup__VariantsArgs;
  args?: PlasmicTemplateGroup__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicTemplateGroup__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicTemplateGroup__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTemplateGroup__ArgProps,
      internalVariantPropNames: PlasmicTemplateGroup__VariantProps
    });

    return PlasmicTemplateGroup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTemplateGroup";
  } else {
    func.displayName = `PlasmicTemplateGroup.${nodeName}`;
  }
  return func;
}

export const PlasmicTemplateGroup = Object.assign(
  // Top-level PlasmicTemplateGroup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    container: makeNodeComponent("container"),

    // Metadata about props expected for PlasmicTemplateGroup
    internalVariantProps: PlasmicTemplateGroup__VariantProps,
    internalArgProps: PlasmicTemplateGroup__ArgProps
  }
);

export default PlasmicTemplateGroup;
/* prettier-ignore-end */
